version: '2.1'

services:
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  some_app:
    build:
      context: .
      dockerfile: Dockerfile_demo
    links:
      - postgres
    depends_on:
      - postgres
